import { v4 as uuidv4 } from 'uuid';
import { RawEngineEvent, SourceEngine, ActorType, KnownEventType } from './timeline/interfaces/timeline-event.interface';

export const SAMPLE_WORKFLOW_ID = '11111111-2222-3333-4444-555555555555';
export const SAMPLE_LEAD_ID = 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee';

export const DEMO_EVENTS: RawEngineEvent[] = [
  {
    workflowId: SAMPLE_WORKFLOW_ID,
    leadId: SAMPLE_LEAD_ID,
    eventType: KnownEventType.LEAD_CREATED,
    sourceEngine: SourceEngine.LEAD_CAPTURE,
    actorType: ActorType.SYSTEM,
    title: 'Lead Created',
    description: 'Website enquiry form submitted by John Doe',
    metadata: { source: 'Google Ads', name: 'John Doe', email: 'john@example.com' },
    deduplicationKey: 'evt_lead_created_demo_01',
    occurredAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    workflowId: SAMPLE_WORKFLOW_ID,
    leadId: SAMPLE_LEAD_ID,
    eventType: KnownEventType.WORKFLOW_STARTED,
    sourceEngine: SourceEngine.WORKFLOW,
    actorType: ActorType.SYSTEM,
    title: 'Workflow Started',
    description: 'Lead Nurturing Automation Workflow initialized',
    metadata: { workflowName: 'Admissions Standard Pipeline v2' },
    deduplicationKey: 'evt_wf_started_demo_02',
    occurredAt: new Date(Date.now() - 3600000 * 23.8).toISOString(),
  },
  {
    workflowId: SAMPLE_WORKFLOW_ID,
    leadId: SAMPLE_LEAD_ID,
    eventType: KnownEventType.MESSAGE_SENT,
    sourceEngine: SourceEngine.RESPONSE,
    actorType: ActorType.BOT,
    title: 'Message Sent',
    description: 'Welcome message delivered via WhatsApp',
    metadata: { channel: 'WhatsApp', deliveryStatus: 'DELIVERED' },
    deduplicationKey: 'evt_msg_sent_demo_03',
    occurredAt: new Date(Date.now() - 3600000 * 23.5).toISOString(),
  },
  {
    workflowId: SAMPLE_WORKFLOW_ID,
    leadId: SAMPLE_LEAD_ID,
    eventType: KnownEventType.BROCHURE_SHARED,
    sourceEngine: SourceEngine.RESPONSE,
    actorType: ActorType.SYSTEM,
    title: 'Brochure Shared',
    description: 'Course Prospectus PDF sent to lead',
    metadata: { pdf: 'brochure_2026.pdf', deliveryStatus: 'OPENED' },
    deduplicationKey: 'evt_brochure_demo_04',
    occurredAt: new Date(Date.now() - 3600000 * 22).toISOString(),
  },
  {
    workflowId: SAMPLE_WORKFLOW_ID,
    leadId: SAMPLE_LEAD_ID,
    eventType: KnownEventType.FEE_STRUCTURE_SHARED,
    sourceEngine: SourceEngine.RESPONSE,
    actorType: ActorType.SYSTEM,
    title: 'Fee Structure Shared',
    description: 'Full course fee details delivered',
    metadata: { tuitionFee: '$4,500 USD' },
    deduplicationKey: 'evt_fee_demo_05',
    occurredAt: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    workflowId: SAMPLE_WORKFLOW_ID,
    leadId: SAMPLE_LEAD_ID,
    eventType: KnownEventType.REMINDER_SCHEDULED,
    sourceEngine: SourceEngine.SCHEDULER,
    actorType: ActorType.SYSTEM,
    title: 'Reminder Scheduled',
    description: 'Counselor follow-up call scheduled',
    metadata: { reminderType: 'COUNSELING_CALL' },
    deduplicationKey: 'evt_reminder_sched_demo_06',
    occurredAt: new Date(Date.now() - 3600000 * 16).toISOString(),
  },
  {
    workflowId: SAMPLE_WORKFLOW_ID,
    leadId: SAMPLE_LEAD_ID,
    eventType: KnownEventType.MEETING_SCHEDULED,
    sourceEngine: SourceEngine.MEETING,
    actorType: ActorType.ADMIN,
    title: 'Meeting Scheduled',
    description: '1-on-1 Counseling session booked with Senior Advisor',
    metadata: { counselor: 'Sarah Jenkins', meetingType: 'Google Meet' },
    deduplicationKey: 'evt_meeting_sched_demo_07',
    occurredAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    workflowId: SAMPLE_WORKFLOW_ID,
    leadId: SAMPLE_LEAD_ID,
    eventType: KnownEventType.MEETING_COMPLETED,
    sourceEngine: SourceEngine.MEETING,
    actorType: ActorType.ADMIN,
    title: 'Meeting Completed',
    description: 'Counseling call finished with positive outcome',
    metadata: { durationMinutes: 28, outcome: 'HIGHLY_INTERESTED' },
    deduplicationKey: 'evt_meeting_comp_demo_08',
    occurredAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    workflowId: SAMPLE_WORKFLOW_ID,
    leadId: SAMPLE_LEAD_ID,
    eventType: KnownEventType.INTERNAL_NOTE_ADDED,
    sourceEngine: SourceEngine.ADMIN,
    actorType: ActorType.ADMIN,
    title: 'Internal Note Added',
    description: 'Lead expressed high interest in evening cohort.',
    metadata: { author: 'Sarah Jenkins', priority: 'HIGH' },
    deduplicationKey: 'evt_note_demo_09',
    occurredAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
];
